export const GETALLCATEGORIES_REQUEST = 'GETALLCATEGORIES_REQUEST';
export const GETALLCATEGORIES_SUCCESS = 'GETALLCATEGORIES_SUCCESS';
export const GETALLCATEGORIES_FAILURE = 'GETALLCATEGORIES_FAILURE';
export const GETTOPRATINGPRODUCT_REQUEST = 'GETTOPRATINGPRODUCT_REQUEST';
export const GETTOPRATINGPRODUCT_SUCCESS = 'GETTOPRATINGPRODUCT_SUCCESS';
export const GETTOPRATINGPRODUCT_FAILURE = 'GETTOPRATINGPRODUCT_FAILURE';
